import 'dart:convert';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:http/http.dart' as http;

class PosApiClient {
  PosApiClient({required this.baseUrl, FlutterSecureStorage? storage}) : _storage = storage ?? const FlutterSecureStorage();
  final String baseUrl; final FlutterSecureStorage _storage;
  Future<void> saveToken(String token)=>_storage.write(key:'pos_jwt',value:token); Future<String?> token()=>_storage.read(key:'pos_jwt'); Future<void> clearToken()=>_storage.delete(key:'pos_jwt'); Future<void> saveCustomerAccessToken(String token)=>_storage.write(key:'customer_access_token',value:token); Future<String?> customerAccessToken()=>_storage.read(key:'customer_access_token'); Future<void> clearCustomerAccessToken()=>_storage.delete(key:'customer_access_token');
  Future<dynamic> _request(String method,String path,{Object? body})async{final t=await token();final h=<String,String>{'Content-Type':'application/json'};if(t!=null)h['Authorization']='Bearer $t';final r=http.Request(method,Uri.parse('$baseUrl$path'))..headers.addAll(h);if(body!=null)r.body=jsonEncode(body);final s=await r.send();final text=await s.stream.bytesToString();dynamic d;if(text.isNotEmpty){try{d=jsonDecode(text);}catch(_){d=text;}}if(s.statusCode<200||s.statusCode>=300)throw Exception(d is String?d:'Request failed: ${s.statusCode}');return d;}
  Future<List<dynamic>> getList(String path)async=>List<dynamic>.from(await _request('GET',path)); Future<dynamic> get(String path)=>_request('GET',path); Future<dynamic> patch(String path,Object body)=>_request('PATCH',path,body:body); Future<dynamic> post(String path,Object body)=>_request('POST',path,body:body); Future<dynamic> put(String path,Object body)=>_request('PUT',path,body:body);
  Future<Map<String,dynamic>> login(String username,String password)async{final d=await _request('POST','/api/auth/login',body:{'username':username,'password':password});await saveToken(d['token']);return Map<String,dynamic>.from(d);} Future<Map<String,dynamic>> me()async=>Map<String,dynamic>.from(await _request('GET','/api/me')); Future<Map<String,dynamic>> settings()async=>Map<String,dynamic>.from(await _request('GET','/api/settings')); Future<Map<String,dynamic>> aiOperate(String message)async=>Map<String,dynamic>.from(await post('/api/ai/operate',{'message':message})); Future<Map<String,dynamic>> aiStatus()async=>Map<String,dynamic>.from(await get('/api/ai/status')); Future<Map<String,dynamic>> aiConfiguration({required String provider,String model='',String apiKey='',String baseUrl=''})async=>Map<String,dynamic>.from(await put('/api/ai/configuration',{'provider':provider,'model':model,'apiKey':apiKey.isEmpty?null:apiKey,'baseUrl':baseUrl.isEmpty?null:baseUrl})); Future<List<dynamic>> discoverAiProviders()async=>getList('/api/ai/providers/discover');
  Future<Map<String,dynamic>> createCustomerSession({String? name,String? phone,String? address,String? notes,String? accessToken})async{final existingAccessToken=accessToken??await customerAccessToken();final body=<String,dynamic>{'name':name,'phone':phone,'address':address,'notes':notes};if(existingAccessToken!=null&&existingAccessToken.isNotEmpty)body['accessToken']=existingAccessToken;final d=Map<String,dynamic>.from(await _request('POST','/api/customer/session',body:body));await saveToken(d['token']);final issuedAccessToken=d['accessToken'];if(issuedAccessToken is String&&issuedAccessToken.isNotEmpty)await saveCustomerAccessToken(issuedAccessToken);return d;}
  Future<List<dynamic>> products()async=>getList('/api/customer/products'); Future<List<dynamic>> promotions()async=>getList('/api/customer/promotions'); Future<List<dynamic>> orders()async=>getList('/api/customer/orders'); Future<Map<String,dynamic>> createOrder({required List<Map<String,dynamic>> items,String orderType='Pickup',String? address,String? notes})async=>Map<String,dynamic>.from(await _request('POST','/api/customer/orders',body:{'items':items,'orderType':orderType,'address':address,'notes':notes})); Future<Map<String,dynamic>> order(int id)async=>Map<String,dynamic>.from(await _request('GET','/api/customer/orders/$id')); Future<Map<String,dynamic>> customerOrderTracking(int orderId)async=>Map<String,dynamic>.from(await get('/api/customer/orders/$orderId/tracking')); Future<Map<String,dynamic>> trackParcel(String trackingCode)async=>Map<String,dynamic>.from(await get('/api/delivery/track/${Uri.encodeComponent(trackingCode)}'));
  Future<List<dynamic>> staffOrders({String? status})async=>getList('/api/orders${status==null?'':'?status=${Uri.encodeQueryComponent(status)}'}'); Future<Map<String,dynamic>> createStaffOrder({int? customerId,int? tableId,required List<Map<String,dynamic>> items,String orderType='Counter',String notes='',String? clientOperationId})async=>Map<String,dynamic>.from(await post('/api/orders',{'customerId':customerId,'tableId':tableId,'items':items,'orderType':orderType,'notes':notes,'clientOperationId':clientOperationId})); Future<Map<String,dynamic>> updateOrderStatus(int id,String status)async=>Map<String,dynamic>.from(await patch('/api/orders/$id/status',{'status':status})); Future<Map<String,dynamic>> collectPayment(int id,{required double amountTendered,String method='Cash',String reference='',String? clientOperationId})async=>Map<String,dynamic>.from(await post('/api/orders/$id/payment',{'amountTendered':amountTendered,'method':method,'reference':reference,'clientOperationId':clientOperationId})); Future<List<dynamic>> orderPayments(int id)async=>getList('/api/orders/$id/payments'); Future<List<dynamic>> tables({bool active=true})async=>getList('/api/tables?active=$active'); Future<List<dynamic>> discoverPrinters()async=>getList('/api/printers/discover'); Future<Map<String,dynamic>> selectPrinter(String documentType)async=>Map<String,dynamic>.from(await post('/api/printers/select',{'documentType':documentType})); Future<Map<String,dynamic>> printReceipt(int orderId)async=>Map<String,dynamic>.from(await post('/api/printers/print-receipt/$orderId',{}));
  Future<List<dynamic>> riderList()async=>getList('/api/delivery/riders'); Future<Map<String,dynamic>> riderAvailability(bool online,{bool available=true})async=>Map<String,dynamic>.from(await post('/api/delivery/riders/me/availability',{'online':online,'available':available})); Future<Map<String,dynamic>> riderLocation(double latitude,double longitude,{double? accuracy,double? speed,double? heading})async=>Map<String,dynamic>.from(await post('/api/delivery/riders/me/location',{'latitude':latitude,'longitude':longitude,'accuracyMeters':accuracy,'speedMetersPerSecond':speed,'headingDegrees':heading})); Future<Map<String,dynamic>> assignRider(int orderId,int riderId)async=>Map<String,dynamic>.from(await post('/api/delivery/orders/$orderId/assign-rider',{'riderId':riderId}));
  Future<List<dynamic>> categories()async=>getList('/api/categories'); Future<Map<String,dynamic>> createCategory(String name,{int sortOrder=0})async=>Map<String,dynamic>.from(await post('/api/categories',{'name':name,'sortOrder':sortOrder})); Future<Map<String,dynamic>> createProduct({required int categoryId,required String name,required double price,String description='',String imageUrl='',bool available=true})async=>Map<String,dynamic>.from(await post('/api/products',{'categoryId':categoryId,'name':name,'price':price,'description':description,'imageUrl':imageUrl,'available':available})); Future<Map<String,dynamic>> updateProduct(int id,{required int categoryId,required String name,required double price,String description='',String imageUrl='',bool available=true})async=>Map<String,dynamic>.from(await put('/api/products/$id',{'categoryId':categoryId,'name':name,'price':price,'description':description,'imageUrl':imageUrl,'available':available}));
  Future<List<dynamic>> conversations()async=>getList('/api/messages/conversations'); Future<List<dynamic>> messages(int id)async=>getList('/api/messages/$id'); Future<Map<String,dynamic>> createConversation(List<String> participants,{String? title})async=>Map<String,dynamic>.from(await post('/api/messages/conversations',{'participants':participants,'title':title})); Future<Map<String,dynamic>> sendMessage(int id,String text)async=>Map<String,dynamic>.from(await post('/api/messages/$id',{'text':text})); Future<void> markRead(int id)async{await _request('POST','/api/messages/$id/read');}
}
