using System.Security.Claims;
using FindUpTo.Pos.Server.Data;
using FindUpTo.Pos.Server.Hubs;
using FindUpTo.Pos.Server.Models;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;

namespace FindUpTo.Pos.Server.Endpoints;

public static class InventoryEndpoints
{
    private static readonly string[] ManageRoles = ["Owner", "Manager", "Admin"];
    public static void MapInventoryEndpoints(this WebApplication app)
    {
        app.MapGet("/api/inventory", async (CoreDbContext db) => Results.Ok(await db.Products.AsNoTracking().Where(x => x.Available).Join(db.ProductInventories.AsNoTracking(), p => p.Id, i => i.ProductId, (p, i) => new { p.Id, p.Name, p.Barcode, p.Price, i.QuantityOnHand, i.ReorderLevel, i.AverageCost, i.TrackInventory, inventoryValue = Math.Round(i.QuantityOnHand * i.AverageCost, 2), unitMargin = Math.Round(p.Price - i.AverageCost, 2), marginPercent = p.Price > 0 ? Math.Round((p.Price - i.AverageCost) / p.Price * 100m, 2) : 0m, i.UpdatedAtUtc }).OrderBy(x => x.Name).ToListAsync())).RequireAuthorization(p => p.RequireRole(ManageRoles));
        app.MapGet("/api/inventory/low-stock", async (CoreDbContext db) => Results.Ok(await db.Products.AsNoTracking().Join(db.ProductInventories.AsNoTracking().Where(i => i.TrackInventory && i.QuantityOnHand <= i.ReorderLevel), p => p.Id, i => i.ProductId, (p, i) => new { p.Id, p.Name, p.Barcode, p.Price, i.QuantityOnHand, i.ReorderLevel, i.AverageCost }).OrderBy(x => x.QuantityOnHand).ToListAsync())).RequireAuthorization(p => p.RequireRole(ManageRoles));
        app.MapGet("/api/inventory/valuation", async (CoreDbContext db) => { var rows = await db.Products.AsNoTracking().Join(db.ProductInventories.AsNoTracking().Where(i => i.TrackInventory), p => p.Id, i => i.ProductId, (p, i) => new { productId = p.Id, productName = p.Name, sellingPrice = p.Price, quantityOnHand = i.QuantityOnHand, averageCost = i.AverageCost, inventoryValue = Math.Round(i.QuantityOnHand * i.AverageCost, 2), retailValue = Math.Round(i.QuantityOnHand * p.Price, 2) }).ToListAsync(); return Results.Ok(new { productCount = rows.Count, inventoryValue = rows.Sum(x => x.inventoryValue), retailValue = rows.Sum(x => x.retailValue), potentialGrossProfit = rows.Sum(x => x.retailValue - x.inventoryValue), products = rows.OrderByDescending(x => x.inventoryValue) }); }).RequireAuthorization(p => p.RequireRole(ManageRoles));
        app.MapPut("/api/products/{id:int}/inventory", async (int id, InventoryUpdateRequest input, ClaimsPrincipal user, CoreDbContext db, IHubContext<PosHub> hub) => { if (input.QuantityOnHand < 0 || input.ReorderLevel < 0) return Results.BadRequest("Inventory quantities cannot be negative."); var product = await db.Products.FindAsync(id); if (product is null) return Results.NotFound(); var inventory = await db.ProductInventories.SingleOrDefaultAsync(x => x.ProductId == id); var old = inventory?.QuantityOnHand ?? 0m; inventory ??= new ProductInventory { ProductId = id }; inventory.QuantityOnHand = input.QuantityOnHand; inventory.ReorderLevel = input.ReorderLevel; inventory.TrackInventory = input.TrackInventory; inventory.UpdatedAtUtc = DateTime.UtcNow; if (inventory.Id == 0) db.ProductInventories.Add(inventory); var delta = input.QuantityOnHand - old; if (delta != 0) db.StockMovements.Add(new StockMovement { ProductId = id, QuantityChange = delta, BalanceAfter = input.QuantityOnHand, UnitCost = inventory.AverageCost, Type = "Adjustment", Reason = input.Reason?.Trim() ?? "", Username = user.Identity?.Name ?? "unknown" }); await db.SaveChangesAsync(); await hub.Clients.All.SendAsync("inventory.updated", new { productId = id, quantityOnHand = inventory.QuantityOnHand, averageCost = inventory.AverageCost, trackInventory = inventory.TrackInventory }); return Results.Ok(inventory); }).RequireAuthorization(p => p.RequireRole(ManageRoles));
        app.MapPost("/api/products/{id:int}/inventory/adjust", async (int id, StockAdjustmentRequest input, ClaimsPrincipal user, CoreDbContext db, IHubContext<PosHub> hub) => { if (input.QuantityChange == 0) return Results.BadRequest("Stock adjustment cannot be zero."); var product = await db.Products.FindAsync(id); if (product is null) return Results.NotFound(); var inventory = await db.ProductInventories.SingleOrDefaultAsync(x => x.ProductId == id); if (inventory is null || !inventory.TrackInventory) return Results.BadRequest("Inventory tracking is not enabled for this product."); var next = inventory.QuantityOnHand + input.QuantityChange; if (next < 0) return Results.BadRequest("Stock cannot become negative."); inventory.QuantityOnHand = next; inventory.UpdatedAtUtc = DateTime.UtcNow; db.StockMovements.Add(new StockMovement { ProductId = id, QuantityChange = input.QuantityChange, BalanceAfter = next, UnitCost = inventory.AverageCost, Type = "Adjustment", Reason = input.Reason?.Trim() ?? "", Username = user.Identity?.Name ?? "unknown" }); await db.SaveChangesAsync(); await hub.Clients.All.SendAsync("inventory.updated", new { productId = id, quantityOnHand = next, averageCost = inventory.AverageCost, trackInventory = true }); return Results.Ok(inventory); }).RequireAuthorization(p => p.RequireRole(ManageRoles));
        app.MapGet("/api/products/{id:int}/inventory/movements", async (int id, CoreDbContext db) => Results.Ok(await db.StockMovements.AsNoTracking().Where(x => x.ProductId == id).OrderByDescending(x => x.CreatedAtUtc).Take(200).ToListAsync())).RequireAuthorization(p => p.RequireRole(ManageRoles));
    }
}
