using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using System.Threading.RateLimiting;
using FindUpTo.Pos.Server.Data;
using FindUpTo.Pos.Server.Endpoints;
using FindUpTo.Pos.Server.Hubs;
using FindUpTo.Pos.Server.Models;
using FindUpTo.Pos.Server.Services;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

var builder = WebApplication.CreateBuilder(args);
builder.Host.ConfigurePosWindowsService();
var connection = builder.Configuration.GetConnectionString("Pos") ?? "Data Source=pos.db";
builder.Services.AddDbContext<CoreDbContext>(options => options.UseSqlite(connection));
builder.Services.AddDataProtection(); builder.Services.AddSingleton<IPasswordHasher<AppUser>, PasswordHasher<AppUser>>();
builder.Services.AddHttpClient("business-ai", client => { client.Timeout = TimeSpan.FromSeconds(90); client.DefaultRequestHeaders.UserAgent.ParseAdd("FindUpTo-POS-AI/1.0"); });
builder.Services.AddScoped<BusinessAiService>(); builder.Services.AddScoped<AiProviderService>(); builder.Services.AddScoped<PromotionPricingService>(); builder.Services.AddScoped<InventoryService>();
builder.Services.AddHostedService<AutomaticBackupHostedService>(); builder.Services.AddHostedService<SyncSchemaHostedService>(); builder.Services.AddHostedService<PushNotificationHostedService>(); builder.Services.AddSignalR(); builder.Services.AddEndpointsApiExplorer(); builder.Services.AddSwaggerGen();
builder.Services.AddRateLimiter(options => { options.AddPolicy("login", context => RateLimitPartition.GetFixedWindowLimiter(context.Connection.RemoteIpAddress?.ToString() ?? "unknown", _ => new FixedWindowRateLimiterOptions { PermitLimit = 10, Window = TimeSpan.FromMinutes(1), QueueLimit = 0, AutoReplenishment = true })); options.AddPolicy("customer-session", context => RateLimitPartition.GetFixedWindowLimiter(context.Connection.RemoteIpAddress?.ToString() ?? "unknown", _ => new FixedWindowRateLimiterOptions { PermitLimit = 5, Window = TimeSpan.FromMinutes(1), QueueLimit = 0, AutoReplenishment = true })); });
var jwtKey = builder.Configuration["Jwt:Key"] ?? Environment.GetEnvironmentVariable("POS_JWT_KEY"); if (string.IsNullOrWhiteSpace(jwtKey) || jwtKey.Length < 32) throw new InvalidOperationException("A JWT signing key of at least 32 characters is required. Configure POS_JWT_KEY or Jwt:Key."); var signingKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtKey));
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(options => { options.TokenValidationParameters = new TokenValidationParameters { ValidateIssuerSigningKey = true, IssuerSigningKey = signingKey, ValidateIssuer = false, ValidateAudience = false, ValidateLifetime = true, NameClaimType = ClaimTypes.Name, RoleClaimType = ClaimTypes.Role }; options.Events = new JwtBearerEvents { OnMessageReceived = context => { var token = context.Request.Query["access_token"]; if (!string.IsNullOrEmpty(token) && context.HttpContext.Request.Path.StartsWithSegments("/hubs/pos")) context.Token = token; return Task.CompletedTask; } }; }); builder.Services.AddAuthorization();
var app = builder.Build(); using (var scope = app.Services.CreateScope()) { var db = scope.ServiceProvider.GetRequiredService<CoreDbContext>(); await PrepareDatabaseAsync(db); await SeedAsync(db, scope.ServiceProvider.GetRequiredService<IPasswordHasher<AppUser>>()); }
if (app.Environment.IsDevelopment()) { app.UseSwagger(); app.UseSwaggerUI(); } app.UseRateLimiter(); app.UseAuthentication(); app.UseAuthorization();
app.MapGet("/health", () => Results.Ok(new { status = "ok", service = "findupto-pos-server" }));
app.MapPost("/api/auth/login", async (LoginRequest request, CoreDbContext db, IPasswordHasher<AppUser> hasher) => { if (string.IsNullOrWhiteSpace(request.Username) || string.IsNullOrEmpty(request.Password)) return Results.Unauthorized(); var user = await db.Users.SingleOrDefaultAsync(x => x.Username == request.Username.Trim() && x.Active); if (user is null || hasher.VerifyHashedPassword(user, user.PasswordHash, request.Password) == PasswordVerificationResult.Failed) return Results.Unauthorized(); var claims = new[] { new Claim(JwtRegisteredClaimNames.Sub, user.Id.ToString()), new Claim(ClaimTypes.Name, user.Username), new Claim(ClaimTypes.Role, user.Role) }; var token = new JwtSecurityToken(claims: claims, expires: DateTime.UtcNow.AddHours(12), signingCredentials: new SigningCredentials(signingKey, SecurityAlgorithms.HmacSha256)); return Results.Ok(new LoginResponse(new JwtSecurityTokenHandler().WriteToken(token), user.Id, user.Username, user.Role)); }).AllowAnonymous().RequireRateLimiting("login");
app.MapGet("/api/me", (ClaimsPrincipal user) => Results.Ok(new { username = user.Identity?.Name, role = user.FindFirstValue(ClaimTypes.Role) })).RequireAuthorization(); app.MapGet("/api/settings", async (CoreDbContext db) => Results.Ok(await db.BusinessSettings.AsNoTracking().SingleAsync())).RequireAuthorization(); app.MapGet("/api/categories", async (CoreDbContext db) => Results.Ok(await db.Categories.AsNoTracking().Where(x => x.Active).OrderBy(x => x.SortOrder).ThenBy(x => x.Name).ToListAsync())).AllowAnonymous(); app.MapGet("/api/products", async (CoreDbContext db, int? categoryId) => { var q = db.Products.AsNoTracking().Where(x => x.Available); if (categoryId.HasValue) q = q.Where(x => x.CategoryId == categoryId.Value); return Results.Ok(await q.OrderBy(x => x.Name).ToListAsync()); }).AllowAnonymous();
app.MapCatalogEndpoints(); app.MapInventoryEndpoints(); app.MapPurchasingEndpoints(); app.MapUserEndpoints(); app.MapWorkflowEndpoints(); app.MapPromotionEndpoints(); app.MapMessagingEndpoints(); app.MapCustomerEndpoints(); app.MapCreditEndpoints(); app.MapReportEndpoints(); app.MapFinanceEndpoints(); app.MapAuditEndpoints(); app.MapCashDrawerEndpoints(); app.MapBackupEndpoints(); app.MapSyncEndpoints(); app.MapPrinterEndpoints(); app.MapTableEndpoints(); app.MapReceiptEndpoints(); app.MapDeviceEndpoints(); app.MapNotificationEndpoints(); app.MapBarcodeEndpoints(); app.MapAiEndpoints(); app.MapHub<PosHub>("/hubs/pos"); app.Run();
static async Task PrepareDatabaseAsync(CoreDbContext db)
{
    var connection = db.Database.GetDbConnection(); await connection.OpenAsync(); await using var command = connection.CreateCommand(); command.CommandText = "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='Users';"; var hasUsersTable = Convert.ToInt64(await command.ExecuteScalarAsync()) > 0; await connection.CloseAsync();
    if (!hasUsersTable) { var allowCreate = string.Equals(Environment.GetEnvironmentVariable("POS_ALLOW_SCHEMA_CREATE"), "true", StringComparison.OrdinalIgnoreCase); if (!allowCreate) throw new InvalidOperationException("The POS database has no schema. Create/apply EF Core migrations first, or explicitly set POS_ALLOW_SCHEMA_CREATE=true for a brand-new database."); await db.Database.EnsureCreatedAsync(); }
    else { await EnsureInventorySchemaAsync(db); await EnsurePurchasingSchemaAsync(db); await EnsureFinanceSchemaAsync(db); await EnsureCreditSchemaAsync(db); }
    await EnsureAiDeliverySchemaAsync(db);
}
static async Task EnsureInventorySchemaAsync(CoreDbContext db) { await db.Database.ExecuteSqlRawAsync("CREATE TABLE IF NOT EXISTS ProductInventories (Id INTEGER NOT NULL CONSTRAINT PK_ProductInventories PRIMARY KEY AUTOINCREMENT, ProductId INTEGER NOT NULL, QuantityOnHand TEXT NOT NULL, ReorderLevel TEXT NOT NULL, TrackInventory INTEGER NOT NULL DEFAULT 0, UpdatedAtUtc TEXT NOT NULL);"); await db.Database.ExecuteSqlRawAsync("CREATE UNIQUE INDEX IF NOT EXISTS IX_ProductInventories_ProductId ON ProductInventories(ProductId);"); await db.Database.ExecuteSqlRawAsync("CREATE TABLE IF NOT EXISTS StockMovements (Id INTEGER NOT NULL CONSTRAINT PK_StockMovements PRIMARY KEY AUTOINCREMENT, ProductId INTEGER NOT NULL, QuantityChange TEXT NOT NULL, BalanceAfter TEXT NOT NULL, Type TEXT NOT NULL, Reason TEXT NOT NULL, Username TEXT NOT NULL, CreatedAtUtc TEXT NOT NULL);"); await db.Database.ExecuteSqlRawAsync("CREATE INDEX IF NOT EXISTS IX_StockMovements_ProductId_CreatedAtUtc ON StockMovements(ProductId, CreatedAtUtc);"); }
static async Task EnsurePurchasingSchemaAsync(CoreDbContext db) { await db.Database.ExecuteSqlRawAsync("CREATE TABLE IF NOT EXISTS Suppliers (Id INTEGER NOT NULL CONSTRAINT PK_Suppliers PRIMARY KEY AUTOINCREMENT, Name TEXT NOT NULL, Phone TEXT NOT NULL, Email TEXT NOT NULL, Address TEXT NOT NULL, Notes TEXT NOT NULL, Active INTEGER NOT NULL DEFAULT 1, CreatedAtUtc TEXT NOT NULL);"); await db.Database.ExecuteSqlRawAsync("CREATE TABLE IF NOT EXISTS PurchaseOrders (Id INTEGER NOT NULL CONSTRAINT PK_PurchaseOrders PRIMARY KEY AUTOINCREMENT, SupplierId INTEGER NOT NULL, Status TEXT NOT NULL, CreatedByUsername TEXT NOT NULL, Notes TEXT NOT NULL, CreatedAtUtc TEXT NOT NULL, UpdatedAtUtc TEXT NOT NULL);"); await db.Database.ExecuteSqlRawAsync("CREATE TABLE IF NOT EXISTS PurchaseOrderItems (Id INTEGER NOT NULL CONSTRAINT PK_PurchaseOrderItems PRIMARY KEY AUTOINCREMENT, PurchaseOrderId INTEGER NOT NULL, ProductId INTEGER NOT NULL, ProductName TEXT NOT NULL, QuantityOrdered TEXT NOT NULL, QuantityReceived TEXT NOT NULL, UnitCost TEXT NOT NULL);"); await db.Database.ExecuteSqlRawAsync("CREATE INDEX IF NOT EXISTS IX_PurchaseOrderItems_PurchaseOrderId ON PurchaseOrderItems(PurchaseOrderId);"); }
static async Task EnsureFinanceSchemaAsync(CoreDbContext db) { await db.Database.ExecuteSqlRawAsync("CREATE TABLE IF NOT EXISTS Expenses (Id INTEGER NOT NULL CONSTRAINT PK_Expenses PRIMARY KEY AUTOINCREMENT, Category TEXT NOT NULL, Description TEXT NOT NULL, Amount TEXT NOT NULL, ExpenseDateUtc TEXT NOT NULL, PaymentMethod TEXT NOT NULL, Reference TEXT NOT NULL, CreatedByUsername TEXT NOT NULL, CreatedAtUtc TEXT NOT NULL);"); await db.Database.ExecuteSqlRawAsync("CREATE INDEX IF NOT EXISTS IX_Expenses_ExpenseDateUtc ON Expenses(ExpenseDateUtc);"); }
static async Task EnsureCreditSchemaAsync(CoreDbContext db) { await db.Database.ExecuteSqlRawAsync("CREATE TABLE IF NOT EXISTS CustomerCreditAccounts (Id INTEGER NOT NULL CONSTRAINT PK_CustomerCreditAccounts PRIMARY KEY AUTOINCREMENT, CustomerId INTEGER NOT NULL, CreditLimit TEXT NOT NULL, Balance TEXT NOT NULL, Active INTEGER NOT NULL DEFAULT 1, UpdatedAtUtc TEXT NOT NULL);"); await db.Database.ExecuteSqlRawAsync("CREATE UNIQUE INDEX IF NOT EXISTS IX_CustomerCreditAccounts_CustomerId ON CustomerCreditAccounts(CustomerId);"); await db.Database.ExecuteSqlRawAsync("CREATE TABLE IF NOT EXISTS CreditTransactions (Id INTEGER NOT NULL CONSTRAINT PK_CreditTransactions PRIMARY KEY AUTOINCREMENT, CustomerCreditAccountId INTEGER NOT NULL, PosOrderId INTEGER NULL, Amount TEXT NOT NULL, Type TEXT NOT NULL, Reference TEXT NOT NULL, Notes TEXT NOT NULL, CreatedByUsername TEXT NOT NULL, CreatedAtUtc TEXT NOT NULL);"); await db.Database.ExecuteSqlRawAsync("CREATE INDEX IF NOT EXISTS IX_CreditTransactions_AccountId_CreatedAtUtc ON CreditTransactions(CustomerCreditAccountId, CreatedAtUtc);"); }
static async Task EnsureAiDeliverySchemaAsync(CoreDbContext db)
{
    var businessColumns = await GetColumnsAsync(db,"BusinessSettings"); foreach(var item in new[]{("AiProvider","ALTER TABLE BusinessSettings ADD COLUMN AiProvider TEXT NOT NULL DEFAULT 'auto';"),("AiModel","ALTER TABLE BusinessSettings ADD COLUMN AiModel TEXT NOT NULL DEFAULT '';"),("AiBaseUrl","ALTER TABLE BusinessSettings ADD COLUMN AiBaseUrl TEXT NOT NULL DEFAULT '';"),("AiApiKeyEncrypted","ALTER TABLE BusinessSettings ADD COLUMN AiApiKeyEncrypted TEXT NOT NULL DEFAULT '';")}) if(!businessColumns.Contains(item.Item1,StringComparer.OrdinalIgnoreCase)) await db.Database.ExecuteSqlRawAsync(item.Item2);
    await db.Database.ExecuteSqlRawAsync("CREATE TABLE IF NOT EXISTS Riders (Id INTEGER NOT NULL CONSTRAINT PK_Riders PRIMARY KEY AUTOINCREMENT, UserId INTEGER NOT NULL, VehicleType TEXT NOT NULL, VehicleNumber TEXT NOT NULL, Online INTEGER NOT NULL DEFAULT 0, Available INTEGER NOT NULL DEFAULT 1, LastSeenAtUtc TEXT NOT NULL);"); await db.Database.ExecuteSqlRawAsync("CREATE UNIQUE INDEX IF NOT EXISTS IX_Riders_UserId ON Riders(UserId);"); await db.Database.ExecuteSqlRawAsync("CREATE TABLE IF NOT EXISTS RiderLocations (Id INTEGER NOT NULL CONSTRAINT PK_RiderLocations PRIMARY KEY AUTOINCREMENT, RiderId INTEGER NOT NULL, Latitude REAL NOT NULL, Longitude REAL NOT NULL, AccuracyMeters REAL NULL, SpeedMetersPerSecond REAL NULL, HeadingDegrees REAL NULL, RecordedAtUtc TEXT NOT NULL);"); await db.Database.ExecuteSqlRawAsync("CREATE INDEX IF NOT EXISTS IX_RiderLocations_RiderId_RecordedAtUtc ON RiderLocations(RiderId,RecordedAtUtc);"); await db.Database.ExecuteSqlRawAsync("CREATE TABLE IF NOT EXISTS DeliveryTrackings (Id INTEGER NOT NULL CONSTRAINT PK_DeliveryTrackings PRIMARY KEY AUTOINCREMENT, OrderId INTEGER NOT NULL, RiderId INTEGER NULL, TrackingCode TEXT NOT NULL, Status TEXT NOT NULL, DeliveryAddress TEXT NOT NULL, DestinationLatitude REAL NULL, DestinationLongitude REAL NULL, UpdatedAtUtc TEXT NOT NULL);"); await db.Database.ExecuteSqlRawAsync("CREATE UNIQUE INDEX IF NOT EXISTS IX_DeliveryTrackings_OrderId ON DeliveryTrackings(OrderId);"); await db.Database.ExecuteSqlRawAsync("CREATE UNIQUE INDEX IF NOT EXISTS IX_DeliveryTrackings_TrackingCode ON DeliveryTrackings(TrackingCode);");
}
static async Task<HashSet<string>> GetColumnsAsync(CoreDbContext db,string tableName){var result=new HashSet<string>(StringComparer.OrdinalIgnoreCase);await using var command=db.Database.GetDbConnection().CreateCommand();command.CommandText=$"PRAGMA table_info({tableName});";if(command.Connection!.State!=System.Data.ConnectionState.Open)await command.Connection.OpenAsync();await using var reader=await command.ExecuteReaderAsync();while(await reader.ReadAsync())result.Add(reader.GetString(1));return result;}
static async Task SeedAsync(CoreDbContext db, IPasswordHasher<AppUser> hasher)
{
    if (!await db.BusinessSettings.AnyAsync()) { db.BusinessSettings.Add(new BusinessSetting { BusinessName = Environment.GetEnvironmentVariable("POS_BUSINESS_NAME")?.Trim() is { Length: > 0 } businessName ? businessName : "FindUpTo POS", Phone = Environment.GetEnvironmentVariable("POS_BUSINESS_PHONE")?.Trim() ?? "", Address = Environment.GetEnvironmentVariable("POS_BUSINESS_ADDRESS")?.Trim() ?? "", TaxPercent = decimal.TryParse(Environment.GetEnvironmentVariable("POS_TAX_PERCENT"), out var tax) ? Math.Clamp(tax, 0m, 100m) : 0m, CurrencyCode = Environment.GetEnvironmentVariable("POS_CURRENCY_CODE")?.Trim().ToUpperInvariant() is { Length: 3 } currencyCode ? currencyCode : "PKR", CurrencySymbol = Environment.GetEnvironmentVariable("POS_CURRENCY_SYMBOL")?.Trim() is { Length: > 0 } currencySymbol ? currencySymbol : "Rs." }); await db.SaveChangesAsync(); }
    var seedUsers = new[] { (Username: "Malik", Role: "Owner", Env: "INITIAL_OWNER_PASSWORD"), (Username: "MK", Role: "Admin", Env: "INITIAL_ADMIN_PASSWORD"), (Username: "WR", Role: "Waiter", Env: "INITIAL_WAITER_PASSWORD"), (Username: "CP", Role: "Counter", Env: "INITIAL_COUNTER_PASSWORD") }; foreach (var item in seedUsers) { if (await db.Users.AnyAsync(x => x.Username == item.Username)) continue; var password = Environment.GetEnvironmentVariable(item.Env); if (string.IsNullOrWhiteSpace(password)) throw new InvalidOperationException($"Missing required initial password environment variable: {item.Env}"); var user = new AppUser { Username = item.Username, Role = item.Role }; user.PasswordHash = hasher.HashPassword(user, password); db.Users.Add(user); } await db.SaveChangesAsync();
}
public partial class Program { }