import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';
import '../../core/api_client.dart';
import '../../core/realtime.dart';

class ParcelTrackingPage extends StatefulWidget { const ParcelTrackingPage({super.key,required this.api,this.initialTrackingCode}); final PosApiClient api; final String? initialTrackingCode; @override State<ParcelTrackingPage> createState()=>_ParcelTrackingPageState(); }
class _ParcelTrackingPageState extends State<ParcelTrackingPage>{final code=TextEditingController();Map<String,dynamic>? data;String? error;bool loading=false;PosRealtime? realtime;StreamSubscription? events;
 @override void initState(){super.initState();if(widget.initialTrackingCode!=null){code.text=widget.initialTrackingCode!;load();}}
 @override void dispose(){events?.cancel();realtime?.dispose();code.dispose();super.dispose();}
 Future<void> load()async{if(code.text.trim().isEmpty)return;setState(()=>loading=true);try{data=await widget.api.trackParcel(code.text.trim());error=null;realtime??=PosRealtime(widget.api);await realtime!.connect();await realtime!.joinTracking(code.text.trim());events??=realtime!.events.stream.listen((event){if(event['type']=='location.updated'&&event['data'] is Map){final d=Map<String,dynamic>.from(event['data']);if(d['trackingCode']==code.text.trim()&&mounted)setState(()=>data={...data!, 'location':{'latitude':d['latitude'],'longitude':d['longitude'],'accuracyMeters':d['accuracyMeters'],'recordedAtUtc':d['recordedAtUtc']}});}});}catch(e){error=e.toString();data=null;}if(mounted)setState(()=>loading=false);}
 @override Widget build(BuildContext context){final location=data?['location'];final lat=(location?['latitude'] as num?)?.toDouble();final lon=(location?['longitude'] as num?)?.toDouble();final destinationLat=(data?['destinationLatitude'] as num?)?.toDouble();final destinationLon=(data?['destinationLongitude'] as num?)?.toDouble();final center=lat!=null&&lon!=null?LatLng(lat,lon):destinationLat!=null&&destinationLon!=null?LatLng(destinationLat,destinationLon):const LatLng(31.4504,73.1385);return Scaffold(appBar:AppBar(title:const Text('Track Parcel')),body:Column(children:[Padding(padding:const EdgeInsets.all(12),child:Row(children:[Expanded(child:TextField(controller:code,decoration:const InputDecoration(labelText:'Tracking code',border:OutlineInputBorder()))),const SizedBox(width:8),FilledButton(onPressed:loading?null:load,child:const Text('Track'))])),if(error!=null)Padding(padding:const EdgeInsets.all(12),child:Text(error!,style:TextStyle(color:Theme.of(context).colorScheme.error))),if(data!=null)ListTile(title:Text('Status: ${data!['status']}'),subtitle:Text('Rider: ${data!['rider']?['username'] ?? 'Not assigned'} • Updated ${data!['updatedAtUtc']}')),Expanded(child:FlutterMap(options:MapOptions(initialCenter:center,initialZoom:14),children:[TileLayer(urlTemplate:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',userAgentPackageName:'com.findupto.pos'),if(lat!=null&&lon!=null)MarkerLayer(markers:[Marker(point:LatLng(lat,lon),width:48,height:48,child:const Icon(Icons.delivery_dining,size:42))]),if(destinationLat!=null&&destinationLon!=null)MarkerLayer(markers:[Marker(point:LatLng(destinationLat,destinationLon),width:48,height:48,child:const Icon(Icons.location_pin,size:42))])]))]));}
}
